### ISSUE TITLE
Delete old webbrowsers?

### ISSUE THREAD

**Issue by RobvanderDoes** [oe-alliance/3rdparty-plugins#10]
As enigma2-plugin-extensions-et-webbrowser_2.0.0-r0_et6x00.ipk & enigma2-plugin-extensions-et-webbrowser_2.0.0-r0_et9x00.ipk have GST <1.0 dependencies: is it OK to delete those plugins?
Obviously that leaves us without HbbTV for those two boxes, but not working versions have no use either, and apparently that's what Xtrend wants :(

**Comment by atvcaptain** [comment]
sure atv have local exclude for long time

**Comment by RobvanderDoes** [comment]
But there are more teams then ATV. I'm not sure if all of them are on GST >1,0
Can we share the ATV-feeds for all OE-A images to get HbbTV?

**Comment by atvcaptain** [comment]
feed are image depend cant not share with other

last info was uk dont need hbbtv

**Comment by RobvanderDoes** [comment]
LOL... there are more countries in the world then the UK..... Many, many more.....

**Comment by RobvanderDoes** [comment]
In other words: it would be very much appreciated if ATV would share their HbbTV solution with other image-teams.

**Comment by RobvanderDoes** [comment]
But there are more teams then ATV. I'm not sure if all of them are on GST >1,0
Is there any OE-A team still using GST <1.0?

**Comment by arn354** [comment]
do you see anyone doing anything on branch 2.3?
Delete them.

**Comment by RobvanderDoes** [comment]
Done.
