### ISSUE TITLE
enigma2-plugin-extensions-serienrecorder_3.6.0_all.ipk - bad control file - cannot create Packages file

### ISSUE THREAD

**Issue by original-birdman** [oe-alliance/3rdparty-plugins#26]
The control file for `enigma2-plugin-extensions-serienrecorder_3.6.0_all.ipk` contains a non-utf8 character, and this means that when `opkg` is trying to create the `Packages` file it aborts:

> Subprocess output:
> Traceback (most recent call last):
>   File "/var/tmp/next-build/oe-alliance/builds/openvix/developer/et8000/tmp/work/et8000-oe-linux/openvix-image/openvix-image-5.2-r000.000/recipe-sysroot-native/usr/bin/opkg-make-index", line 125, in <module>
>     pkg = opkg.Package(abspath, relpath=pkg_dir)
>   File "/var/tmp/next-build/oe-alliance/builds/openvix/developer/et8000/tmp/work/et8000-oe-linux/openvix-image/openvix-image-5.2-r000.000/recipe-sysroot-native/usr/bin/opkg.py", line 175, in __init__
>     self.read_control(control)
>   File "/var/tmp/next-build/oe-alliance/builds/openvix/developer/et8000/tmp/work/et8000-oe-linux/openvix-image/openvix-image-5.2-r000.000/recipe-sysroot-native/usr/bin/opkg.py", line 222, in read_control
>     line = line.decode()
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 43: invalid start byte

The issue is the ü in 

> Description: Erstellt automatisiert Timer f�r deine Lieblings-Serien - nie mehr eine Folge verpassen!

It's been put in as an "extended ASCII" character (0xfc) but should (==**must**) be 0xc3 0xbc (U+00fc).

**Comment by AbuBaniaz** [comment]
Current branch builds. 

Here is a repackaged ipk.
[enigma2-plugin-extensions-serienrecorder_3.6.0_all.ipk.zip](https://github.com/oe-alliance/3rdparty-plugins/files/1592464/enigma2-plugin-extensions-serienrecorder_3.6.0_all.ipk.zip)

**Comment by RobvanderDoes** [comment]
The package should have been renamed (to something like 'enigma2-plugin-extensions-serienrecorder_3.6.0rc1_all.ipk' or so) so OPKG understands that it should update to this version. I tried to do that, but opening the package gives me all sorts of errors.

**Comment by atvcaptain** [comment]
its nothing new only issue with new opkg 0.35 use this was a fix for oe-a 4.2
