### ISSUE TITLE
Update iSettingE2

### ISSUE THREAD

**Issue by CloudItaly** [oe-alliance/3rdparty-plugins#27]
Add this: 
enigma2-plugin-extensions-isettinge2-3.4.1-oe2.0-all-mips.ipk

from http://www.isettinge2.com/

**Comment by ghost** [comment]
done https://github.com/oe-alliance/oe-alliance-core/commit/5420c57f5262b6ecbea1f930add58334b2529872#diff-d56603dfd325f1f90f71169d9d4c3591
