### ISSUE TITLE
Extended NumberZap - Dutch Translation 02-02-2020

### ISSUE THREAD

**Issue by Snoete** [oe-alliance/3rdparty-plugins#35]
I made a Dutch Translation for this Plugin, would appreciate it if it makes it into the .ipk !

[Extended NumberZap_NL_02-02-2020.zip](https://github.com/oe-alliance/3rdparty-plugins/files/4145243/Extended.NumberZap_NL_02-02-2020.zip)

**Comment by mike-99** [comment]
Vieleicht mal an der Quelle anfragen?! https://github.com/Dima73/Extended-NumberZap/commits/master
Gab zwar schon länger keine Änderungen, aber vieleicht wird es dort übernommen.

**Comment by mike-99** [comment]
https://github.com/oe-alliance/3rdparty-plugins/commit/4f16b692f152d5a5a5262958705472dfa0491901

Vers 1.21 incl nl.po
