### ISSUE TITLE
Please delete enigma2-plugin-extensions-tmbd_6.7_all.ipk

### ISSUE THREAD

**Issue by Dima73** [oe-alliance/3rdparty-plugins#5]
This not work (kinopoisk ru type)
New version this https://github.com/Dima73/enigma2-plugin-extensions-tmbd

**Comment by RobvanderDoes** [comment]
Can you upload an IPK please?

**Comment by Dima73** [comment]
Ok,make ipk.Please wait.

**Comment by RobvanderDoes** [comment]
Please wait Dima; I'll add the Dutch translation.

**Comment by RobvanderDoes** [comment]
Here you are:
[nl.zip](https://github.com/oe-alliance/3rdparty-plugins/files/442633/nl.zip)

**Comment by Dima73** [comment]
done
https://github.com/Dima73/enigma2-plugin-extensions-tmbd/blob/master/enigma2-plugin-extensions-tmbd_7.4_all.ipk

**Comment by RobvanderDoes** [comment]
Thanks: updated feeds.

**Comment by RobvanderDoes** [comment]
Working well, but 2 questions:
1- When using a 1080-skin, the embedded screens are quite small.
2- When both the upper and the lower part of the screen show a scrollbar: how can one switch from one screen-part to the other to scroll up/down?

![tmbd 02](https://cloud.githubusercontent.com/assets/1040294/18076678/42916536-6e80-11e6-8c78-c79795a6faa5.jpg)
![tmbd 01](https://cloud.githubusercontent.com/assets/1040294/18076679/42973272-6e80-11e6-96f8-23e9328f7e26.jpg)

**Comment by RobvanderDoes** [comment]
OK, found #2 :)
For #1 see how much space can be gained:
![tmbd 04](https://cloud.githubusercontent.com/assets/1040294/18077670/90b749ae-6e87-11e6-9a80-688c42f2f088.jpg)
![tmbd 03](https://cloud.githubusercontent.com/assets/1040294/18077671/90be6658-6e87-11e6-951e-4846bf8b5df7.jpg)

**Comment by Dima73** [comment]
1)Yes, need add  1080-skin.
But I have no strength to this complex work.
You do not want to do it yourself?
2)Bouq -/+

**Comment by RobvanderDoes** [comment]
OK, I'll create the same screens as the embedded ones for 1080.
But you'll have to embed it into the source file, including the correct choosing of the correct sized screens :)

**Comment by Dima73** [comment]
Ok,done.
https://github.com/Dima73/enigma2-plugin-extensions-tmbd/commit/0054e8b131c5790f5d24f339feeb30301b400101
https://github.com/Dima73/enigma2-plugin-extensions-sundtekcontrolcenter/commit/07c10dbb1d634ddb11beb874e0fc9659c233748d
Thanks...
