### ISSUE TITLE
sundtekcontrolcenter

### ISSUE THREAD

**Issue by Dima73** [oe-alliance/3rdparty-plugins#6]
For info...
New version this https://github.com/Dima73/enigma2-plugin-extensions-sundtekcontrolcenter

**Comment by RobvanderDoes** [comment]
I prefer to use the official ones from http://www.sundtek.de/media/ .

**Comment by atvcaptain** [comment]
dima73 version was ok , you can use

**Comment by RobvanderDoes** [comment]
OK, will do.

**Comment by RobvanderDoes** [comment]
Thanks, updated feeds.
